apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DB_URL: dGVhbTItcmV2aGlyZS5jemF1ZXM2d210eHMudXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
  DB_USERNAME: YWRtaW4=  
  DB_PASSWORD: MTIzNDU2Nzg=  
  DB_PORT: MzMwNg==